#!/bin/sh
#
# $Id: run,v 1.3 2002-04-19 03:22:27 dan Exp $
#
# Copyright (c) 2001-2002 DVL Software
#
echo starting!
exec setuidgid lists-test envdir ./env /usr/bin/perl /home/lists-test/scripts/main-page-update.pl
